export const environment = {
  production: true,
  name: 'admin.azonno.com',
  domain: 'admin.azonno.com',
  baseLink: 'https://api.azonno.com',
  paymentBaseLink: 'https://api.azonno.com',
  apiBaseLink: 'https://api.azonno.com',
  ftpBaseLink: 'https://api.azonno.com',
  ftpPrefixPath: 'https://api.azonno.com/api/upload/images',
  apiBaseLinkSaleecom: 'https://api.azonno.com',
  ftpPrefix: '/api',
  userLoginUrl: 'login',
  userBaseUrl: '',
  appBaseUrl: '/',
  adminBaseUrl: '',
  adminLoginUrl: 'login',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  vendorLoginUrl: 'login',
  vendorBaseUrl: '',
  vendorSecretKey: 'saleecoMVendoRLogiNSecreT2025',
  VERSION: 2,
};

