import {AdminMenu} from '../../interfaces/core/admin-menu.interface';


export const SUPER_ADMIN_MENU: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  // {
  //   id: 1,
  //   name: 'Incomplete Orders',
  //   hasSubMenu: false,
  //   routerLink: 'order/all-incomplete-order',
  //   icon: 'reorder',
  //   subMenus: [],
  // },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  {
    id: 4,
    name: 'Customization',
    hasSubMenu: true,
    routerLink: null,
    icon: 'tune',
    subMenus: [
      {
        id: 2,
        name: 'Carousel',
        hasSubMenu: true,
        routerLink: 'customization/all-carousel',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: 'Banner',
        hasSubMenu: true,
        routerLink: 'customization/all-banner',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'PopUp',
        hasSubMenu: true,
        routerLink: 'customization/all-popup',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Website Information',
        hasSubMenu: true,
        routerLink: 'customization/website-information',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Theme View',
        hasSubMenu: true,
        routerLink: 'customization/theme-view',
        icon: 'arrow_right',
      },
      // {
      //   id: 7,
      //   name: 'Themes',
      //   hasSubMenu: false,
      //   routerLink: 'customization/themes',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 8,
      //   name: 'Page View',
      //   hasSubMenu: true,
      //   routerLink: 'customization/page-view',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
      // {
      //   id: 7,
      //   name: 'Skin Type',
      //   hasSubMenu: true,
      //   routerLink: 'catalog/all-skin-type',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 8,
      //   name: 'Skin Concern',
      //   hasSubMenu: true,
      //   routerLink: 'catalog/all-skin-concern',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: true,
    routerLink: null,
    icon: 'web',
    subMenus: [
      {
        id: 1,
        name: 'Customizable Landing page',
        hasSubMenu: true,
        routerLink: 'landing-page/all-customizable-landing-page',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: 'Ready Landing page',
        hasSubMenu: true,
        routerLink: 'landing-page/all-fixed-landing-page',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },

  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 77,
    name: 'Coupon',
    hasSubMenu: false,
    routerLink: 'coupon/all-coupon',
    icon: 'payments',
    subMenus: [],
  },

  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 122,
    name: 'Address',
    hasSubMenu: true,
    routerLink: null,
    icon: 'home',
    subMenus: [
      {
        id: 1,
        name: 'All Division',
        hasSubMenu: true,
        routerLink: 'address/all-divisions',
        icon: 'arrow_right',
      },
      // {
      //   id: 2,
      //   name: 'Area',
      //   hasSubMenu: true,
      //   routerLink: 'address/all-area',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 3,
      //   name: 'Zone',
      //   hasSubMenu: true,
      //   routerLink: 'address/all-zone',
      //   icon: 'arrow_right',
      // }
    ],
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },
  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },
  // {
  //   id: 19,
  //   name: 'Tutorial Page',
  //   hasSubMenu: false,
  //   routerLink: 'tutorial',
  //   icon: 'videocam',
  //   subMenus: [],
  // },
  // {
  //   id: 117,
  //   name: 'Subscription',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Subscription',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/all-subscription',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Subscription Report',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/subscription-report',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'My Subscription',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/my-subscription',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 317,
  //   name: 'Manager',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Log Manager',
  //       hasSubMenu: true,
  //       routerLink: 'manager/all-log',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'All Trash Manager',
  //       hasSubMenu: true,
  //       routerLink: 'manager/all-trash',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 318,
  //   name: 'Expense',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Expense',
  //       hasSubMenu: true,
  //       routerLink: 'expense/all-expense',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },

  {
    id: 10,
    name: 'Admin Control',
    hasSubMenu: false,
    routerLink: 'admin',
    icon: 'admin_panel_settings',
    subMenus: [],
  },
  // {
  //   id: 124,
  //   name: 'Blog Area',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'rss_feed',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'Blog',
  //       hasSubMenu: true,
  //       routerLink: 'blog/all-blog',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Blog Comment',
  //       hasSubMenu: true,
  //       routerLink: 'blog/all-comment',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 1255,
  //   name: 'All Trash',
  //   hasSubMenu: false,
  //   routerLink: 'trash',
  //   icon: 'auto_delete',
  //
  //   subMenus: [],
  // },

  {
    id: 109,
    name: 'Support',
    hasSubMenu: false,
    routerLink: 'support',
    icon: 'help_center',
    subMenus: [],
  },

  {
    id: 12,
    name: 'Tutorials',
    hasSubMenu: false,
    routerLink: 'tutorial',
    icon: 'smart_display',

    subMenus: [],
  },

  {
    id: 1132,
    name: 'Expense',
    hasSubMenu: true,
    routerLink: null,
    icon: 'payments',
    subMenus: [
      {
        id: 1,
        name: 'Expense',
        hasSubMenu: true,
        routerLink: 'expense/all-expense',
        icon: 'arrow_right',
      },
    ],
  },

  {
    id: 11352,
    name: 'IP Block',
    hasSubMenu: true,
    routerLink: null,
    icon: 'dns',
    subMenus: [
      {
        id: 1,
        name: 'IP Block',
        hasSubMenu: true,
        routerLink: 'ip-block/all-ip-block',
        icon: 'arrow_right',
      },
    ],
  },

  // {
  //   id: 122,
  //   name: 'New Release',
  //   hasSubMenu: false,
  //   routerLink: 'new-release-report',
  //   icon: 'verified',
  //   subMenus: [],
  // },

  // {
  //   id: 123,
  //   name: 'Login Device',
  //   hasSubMenu: false,
  //   routerLink: 'login-all-device',
  //   icon: 'login',
  //
  //   subMenus: [],
  // },

  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },

  {
    id: 121,
    name: 'Domain Info',
    hasSubMenu: false,
    routerLink: 'domain-information',
    icon: 'language',
    subMenus: [],
  },


];

//Super Counter Menu
export const ADMIN_MENU: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  {
    id: 4,
    name: 'Customization',
    hasSubMenu: true,
    routerLink: null,
    icon: 'tune',
    subMenus: [
      {
        id: 2,
        name: 'Carousel',
        hasSubMenu: true,
        routerLink: 'customization/all-carousel',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: 'Banner',
        hasSubMenu: true,
        routerLink: 'customization/all-banner',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'PopUp',
        hasSubMenu: true,
        routerLink: 'customization/all-popup',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Website Information',
        hasSubMenu: true,
        routerLink: 'customization/website-information',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Theme View',
        hasSubMenu: true,
        routerLink: 'customization/theme-view',
        icon: 'arrow_right',
      },
      // {
      //   id: 6,
      //   name: 'Page View',
      //   hasSubMenu: true,
      //   routerLink: 'customization/page-view',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: false,
    routerLink: 'landing-page/all-landing',
    icon: 'web',
    subMenus: [],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },
  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },
  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },
  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },

];

//Manager Menu
export const MANAGER_MENU: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  {
    id: 4,
    name: 'Customization',
    hasSubMenu: true,
    routerLink: null,
    icon: 'tune',
    subMenus: [
      {
        id: 2,
        name: 'Carousel',
        hasSubMenu: true,
        routerLink: 'customization/all-carousel',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: 'Banner',
        hasSubMenu: true,
        routerLink: 'customization/all-banner',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'PopUp',
        hasSubMenu: true,
        routerLink: 'customization/all-popup',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Website Information',
        hasSubMenu: true,
        routerLink: 'customization/website-information',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Theme View',
        hasSubMenu: true,
        routerLink: 'customization/theme-view',
        icon: 'arrow_right',
      },
      // {
      //   id: 6,
      //   name: 'Page View',
      //   hasSubMenu: true,
      //   routerLink: 'customization/page-view',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: false,
    routerLink: 'landing-page/all-landing',
    icon: 'web',
    subMenus: [],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },
  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },
  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },
  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },

];

export const EDITOR_MENU: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  {
    id: 4,
    name: 'Customization',
    hasSubMenu: true,
    routerLink: null,
    icon: 'tune',
    subMenus: [
      {
        id: 2,
        name: 'Carousel',
        hasSubMenu: true,
        routerLink: 'customization/all-carousel',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: 'Banner',
        hasSubMenu: true,
        routerLink: 'customization/all-banner',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'PopUp',
        hasSubMenu: true,
        routerLink: 'customization/all-popup',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Website Information',
        hasSubMenu: true,
        routerLink: 'customization/website-information',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Theme View',
        hasSubMenu: true,
        routerLink: 'customization/theme-view',
        icon: 'arrow_right',
      },
      // {
      //   id: 7,
      //   name: 'Themes',
      //   hasSubMenu: false,
      //   routerLink: 'customization/themes',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 8,
      //   name: 'Page View',
      //   hasSubMenu: true,
      //   routerLink: 'customization/page-view',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: false,
    routerLink: 'landing-page/all-landing',
    icon: 'web',
    subMenus: [],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },
  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },

  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },

  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },

];
